logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
